---
af: &1
- one
- other
ak: *1
am: *1
ar: &2
- zero
- one
- two
- few
- many
- other
ars: *2
as: *1
asa: *1
ast: *1
az: *1
be: &3
- one
- few
- many
- other
bem: *1
bez: *1
bg: *1
bh: *1
bm: &4
- other
bn: *1
bo: *4
br: &5
- one
- two
- few
- many
- other
brx: *1
bs: &6
- one
- few
- other
ca: *1
ce: *1
cgg: *1
chr: *1
ckb: *1
cs: *3
cy: *2
da: *1
de: *1
dsb: &7
- one
- two
- few
- other
dv: *1
dz: *4
ee: *1
el: *1
en: *1
eo: *1
es: *1
et: *1
eu: *1
fa: *1
ff: *1
fi: *1
fil: *1
fo: *1
fr: *1
fur: *1
fy: *1
ga: *5
gd: *7
gl: *1
gsw: *1
gu: *1
guw: *1
gv: *5
ha: *1
haw: *1
he: &8
- one
- two
- many
- other
hi: *1
hr: *6
hsb: *7
hu: *1
hy: *1
id: *4
ig: *4
ii: *4
in: *4
io: *1
is: *1
it: *1
iu: &9
- one
- two
- other
iw: *8
ja: *4
jbo: *4
jgo: *1
ji: *1
jmc: *1
jv: *4
jw: *4
ka: *1
kab: *1
kaj: *1
kcg: *1
kde: *4
kea: *4
kk: *1
kkj: *1
kl: *1
km: *4
kn: *1
ko: *4
ks: *1
ksb: *1
ksh: &10
- zero
- one
- other
ku: *1
kw: *9
ky: *1
lag: *10
lb: *1
lg: *1
lkt: *4
ln: *1
lo: *4
lt: *3
lv: *10
mas: *1
mg: *1
mgo: *1
mk: *1
ml: *1
mn: *1
mo: *6
mr: *1
ms: *4
mt: *3
my: *4
nah: *1
naq: *9
nb: *1
nd: *1
ne: *1
nl: *1
nn: *1
nnh: *1
no: *1
nqo: *4
nr: *1
nso: *1
ny: *1
nyn: *1
om: *1
or: *1
os: *1
pa: *1
pap: *1
pl: *3
prg: *10
ps: *1
pt: *1
pt_PT: *1
rm: *1
ro: *6
rof: *1
root: *4
ru: *3
rwk: *1
sah: *4
saq: *1
sc: *1
scn: *1
sd: *1
sdh: *1
se: *9
seh: *1
ses: *4
sg: *4
sh: *6
shi: *6
si: *1
sk: *3
sl: *7
sma: *9
smi: *9
smj: *9
smn: *9
sms: *9
sn: *1
so: *1
sq: *1
sr: *6
ss: *1
ssy: *1
st: *1
sv: *1
sw: *1
syr: *1
ta: *1
te: *1
teo: *1
th: *4
ti: *1
tig: *1
tk: *1
tl: *1
tn: *1
to: *4
tr: *1
ts: *1
tzm: *1
ug: *1
uk: *3
ur: *1
uz: *1
ve: *1
vi: *4
vo: *1
vun: *1
wa: *1
wae: *1
wo: *4
xh: *1
xog: *1
yi: *1
yo: *4
yue: *4
zh: *4
zu: *1
